apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-external-secrets
  namespace: access-control
spec:
  refreshInterval: 1h # 每一小時自動與 GCP Secret Manager 同步一次最新的密碼
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: app-secrets # 這將會在 GKE 中動態自動建立一個名為 app-secrets 的 K8s Secret
    creationPolicy: Owner
  data:
  - secretKey: CLICKHOUSE_PASSWORD
    remoteRef:
      key: CLICKHOUSE_PASSWORD # GCP Secret Manager 中的 Secret 名稱
