apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-reader-sa
  namespace: access-control
  annotations:
    iam.gke.io/gcp-service-account: secret-accessor@access-api-497314.iam.gserviceaccount.com
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: access-control
spec:
  provider:
    gcpsm:
      projectID: access-api-497314
      # 透過我們設定好的 ServiceAccount 去 GCP 讀取
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: secret-reader-sa
