apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-api
  namespace: access-control
  labels:
    app: admin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-api
  template:
    metadata:
      labels:
        app: admin-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8081"
    spec:
      containers:
      - name: admin-api
        image: asia-east1-docker.pkg.dev/access-api-497314/access-api-repo/admin-api:v1
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        env:
        - name: HTTP_ADDR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HTTP_ADDR_ADMIN
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_BROKERS
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_TOPIC_PERMISSION
---
apiVersion: v1
kind: Service
metadata:
  name: admin-api
  namespace: access-control
spec:
  selector:
    app: admin-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
