apiVersion: 1

contactPoints:
  - orgId: 1
    name: security-slack
    receivers:
      - uid: slack-security
        type: slack
        settings:
          recipient: "#security-alerts"
          mentionChannel: here
          url: "https://hooks.slack.com/services/REPLACE/ME/IN_GRAFANA_UI"
        disableResolveMessage: false
